# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

defined?(Dotenv) && Dotenv.load

Motion::Project::App.setup do |app|
  app.name                 = 'ProchainBus'
  app.deployment_target    = '7.0'
  app.version              = '3'
  app.short_version        = '3'
  app.identifier           = "com.novelys.com.monprochainbus"
  app.fonts                = ['icomoon.ttf', 'oswald.light.ttf', 'DroidSans-Bold.ttf']
  app.icons                = ["icon-40.png", "icon-76.png", "icon-80.png", "icon-120.png", "icon-152.png"]
  app.provisioning_profile = ENV['PROVISIONING'] if ENV['PROVISIONING']

  app.info_plist['UIViewControllerBasedStatusBarAppearance'] = false

  app.pods do
    pod 'Airbrake-iOS', '~> 3.1'
  end
end
